module CenterServerOrb
{
    typedef sequence<string> list;
    interface CenterServer
    {
          exception except{
                  string reason;
                };
          string createTRecord(in string managerId,in string firstName,in string lastName,in string address,in string phone,in string specialization,in string location);
          string createSRecord(in string managerId,in string firstName,in string lastName,in list courseRegistered,in string status,in string statusDate);
          string getRecordCounts(in string managerId);
          string editRecord(in string managerId,in string recordID,in string fieldName,in string newValue) raises(except);
          oneway void shutdown();
    };
};
